### ISSUE TITLE
it_IT -> en?

### ISSUE THREAD

**Issue by 3LOK** [wix/google-maps-locales#1]
If you add the following to the test file, it fails:

GoogleMapsLocales.bestGoogleMapsLocaleFor("it_IT").should.equal("it")

Italian is a very popular language in many regions of the world. Even in Israel there are a large number of Italian speaking people. Yet, the author of this component, along with the general locales component, seem to have a problem against Italians. During these days, any kind of discrimination should be abolished completely. 

Please fix.

**Comment by dleshem** [comment]
Fixed in 1.0.2
